{"errorMessage": "An error occurred (InvalidS3ObjectException) when calling the DetectModerationLabels operation: Unable to get object metadata from S3. Check object key, region and/or access permissions.", "errorType": "InvalidS3ObjectException", "requestId": "5b345753-fb40-47ca-8a28-c90866fbc04b", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 28, in lambda_handler\n    response = rekognition.detect_moderation_labels(\n", "  File \"/var/runtime/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}